"""Quantitative analytics, optimization, backtest and pricing ports.

This top-level package mirrors the :mod:`indiciumforge_core.factors`
domain-packaging pattern: each submodule declares a :class:`typing.Protocol`
port plus frozen-dataclass request/result models, ships one or more concrete
adapters, and exposes a registry + pack loader for runtime discovery.

The package stays *infrastructure-free*: adapters lazily import their heavy
dependencies (statsmodels, cvxpy, ...) behind ``_require_*`` helpers so that
``import indiciumforge_core.quant`` succeeds with only the core install.
"""

from indiciumforge_core.quant.analytics import (
    FACTOR_ANALYTICS_PACK_SCHEMA,
    FactorAnalyticsLoadError,
    FactorAnalyticsPort,
    FactorAnalyticsRegistry,
    FactorEvaluationRequest,
    FactorEvaluationResult,
    FactorReturnStat,
    ICStat,
    LoadedAnalyticsPack,
    StatsmodelsFactorEngine,
    TurnoverStat,
    factor_panel_from_signals,
    load_analytics_from_config,
    load_analytics_from_entry_points,
    load_analytics_pack,
)
from indiciumforge_core.quant.backtest import (
    BACKTEST_PACK_SCHEMA,
    BacktesterLoadError,
    BacktestPort,
    BacktestRegistry,
    BacktestRequest,
    BacktestResult,
    DuplicateBacktesterError,
    LoadedBacktestPack,
    VectorizedBacktester,
    load_backtest_pack,
    load_backtesters_from_config,
    load_backtesters_from_entry_points,
)
from indiciumforge_core.quant.portfolio import (
    PORTFOLIO_PACK_SCHEMA,
    CvxpyOptimizer,
    DuplicateOptimizerError,
    LoadedPortfolioPack,
    PortfolioOptimizationPort,
    PortfolioOptimizationRegistry,
    PortfolioOptimizationRequest,
    PortfolioOptimizationResult,
    PortfolioOptimizerLoadError,
    load_portfolio_optimizers_from_config,
    load_portfolio_optimizers_from_entry_points,
    load_portfolio_pack,
)
from indiciumforge_core.quant.pricing import (
    PRICING_PACK_SCHEMA,
    BlackScholesPricer,
    DuplicatePricerError,
    LoadedPricingPack,
    PricerLoadError,
    PricingPort,
    PricingRegistry,
    PricingRequest,
    PricingResult,
    load_pricers_from_config,
    load_pricers_from_entry_points,
    load_pricing_pack,
)

__all__ = [
    "FACTOR_ANALYTICS_PACK_SCHEMA",
    "FactorAnalyticsLoadError",
    "FactorAnalyticsPort",
    "FactorAnalyticsRegistry",
    "FactorEvaluationRequest",
    "FactorEvaluationResult",
    "FactorReturnStat",
    "ICStat",
    "LoadedAnalyticsPack",
    "StatsmodelsFactorEngine",
    "TurnoverStat",
    "factor_panel_from_signals",
    "load_analytics_from_config",
    "load_analytics_from_entry_points",
    "load_analytics_pack",
    "PORTFOLIO_PACK_SCHEMA",
    "CvxpyOptimizer",
    "DuplicateOptimizerError",
    "LoadedPortfolioPack",
    "PortfolioOptimizerLoadError",
    "PortfolioOptimizationPort",
    "PortfolioOptimizationRegistry",
    "PortfolioOptimizationRequest",
    "PortfolioOptimizationResult",
    "load_portfolio_optimizers_from_config",
    "load_portfolio_optimizers_from_entry_points",
    "load_portfolio_pack",
    "BACKTEST_PACK_SCHEMA",
    "BacktesterLoadError",
    "BacktestPort",
    "BacktestRegistry",
    "BacktestRequest",
    "BacktestResult",
    "DuplicateBacktesterError",
    "LoadedBacktestPack",
    "VectorizedBacktester",
    "load_backtesters_from_config",
    "load_backtesters_from_entry_points",
    "load_backtest_pack",
    "PRICING_PACK_SCHEMA",
    "BlackScholesPricer",
    "DuplicatePricerError",
    "LoadedPricingPack",
    "PricerLoadError",
    "PricingPort",
    "PricingRegistry",
    "PricingRequest",
    "PricingResult",
    "load_pricers_from_config",
    "load_pricers_from_entry_points",
    "load_pricing_pack",
]
